services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ai_investment
      POSTGRES_USER: ai_app
      POSTGRES_PASSWORD: Cr7m10p7!!
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      CORS_ORIGINS: http://localhost:3000,http://localhost:5173
      DATABASE_URL: postgresql://ai_app:Cr7m10p7!!@postgres:5432/ai_investment
      REDIS_URL: redis://redis:6379/0
      GEMINI_API_KEY: AIzaSyC9hhaZsxIGRIrsrR3lrG9trIzDp_TuLCY
      GEMINI_MODEL: gemini-2.0-flash
      ALPHA_VANTAGE_KEY: J0RMGODDUVCQ5FG2
      NEWSAPI_KEY: 29c2a80f3a02489d89f671b696499016
      FINNHUB_KEY: "d82nf61r01qmgc0gqe10d82nf61r01qmgc0gqe1g"
    volumes:
      - backend_data:/app/data
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - redis
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  backend_data:
  postgres_data:
  redis_data:
